# Use root/meli as user/password credentials
version: '3'

services:

  flask-api:
    build: .
    hostname: flask-api
    container_name: flask-api
    expose:
      - 5000
    ports:
      - 8080:5000
    volumes:
      - .:/opt/app
    environment:
      MONGODB_URL: mongodb://root:meli@mongo-meli:27017/
      MONGODB_DATABASE: meli_interations
      MONGODB_COLLECTION: interations
    links:
      - mongo-meli
    depends_on:
      - mongo-meli
    networks:
      - meli-network

  mongo-meli:
    image: mongo
    hostname: mongo-meli
    container_name: mongo-meli
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: meli
    networks: 
      - meli-network
  
  mongo-meli-express:
    image: mongo-express
    container_name: mongo-meli-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo-meli
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: meli
    depends_on:
      - mongo-meli
    networks: 
      - meli-network

networks: 
  meli-network:
    driver: bridge